name: Build Docker Image and Push to Artifact Registry

on:
  workflow_call:
    inputs:
      DOCKERFILE:
        required: true
        type: string
      DOCKER_IMAGE_NAME:
        required: true
        type: string
      ARTIFACT_REGISTRY_URL:
        required: true
        type: string
      LATEST_TAG:
        required: false
        type: string
        default: "latest"

    secrets:
      GCLOUD_CREDENTIALS:
        required: true
      TURBO_TOKEN:
        required: true
      TURBO_TEAM:
        required: true

jobs:
  build_and_push_docker_image:
    name: 🐳 Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Yarn cache directory
        run: |
          mkdir -p /tmp/yarn-cache
          yarn config set cache-folder /tmp/yarn-cache

      - name: Cache Yarn packages
        uses: actions/cache@v3
        with:
          path: /tmp/yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.ARTIFACT_REGISTRY_URL }}
          username: _json_key
          password: ${{ secrets.GCLOUD_CREDENTIALS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        with:
          context: .
          file: ${{ inputs.DOCKERFILE }}
          push: true
          tags: |
            ${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.LATEST_TAG }}
            ${{ inputs.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ inputs.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ inputs.DOCKER_IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM=${{ secrets.TURBO_TEAM }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          # Mount both Yarn and Turborepo cache directories
          build-contexts: |
            yarn-cache=/tmp/yarn-cache
